### ISSUE TITLE
Black

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/fikspunktsregister#12]
So far, I haven't added [black](https://black.readthedocs.io/en/stable/) to my tool chain. Figure out what is the best place to add it.

**Comment by bjornharrtell** [comment]
Ok, I think we should use pre-commit hook locally and a diff check on CI so that it will not accept any PR that gives a diff after running black at CI.

**Comment by AsgerPetersen** [comment]
I have been running this continually on all files for a while now. It would be nice to have this in a git hook. But...

**Comment by kbevers** [comment]
> But...

yeah? :-)

I've been trying to do that but the recommended way of doing it doesn't work with conda. Apparently a more recent version of virtualenv is needed than what is available. Rather annoying.

**Comment by AsgerPetersen** [comment]
My point was that I am running black on everything here. So as long as no one else is touching the code everything is good 😀

**Comment by kbevers** [comment]
> So as long as no one else is touching the code everything is good 😀

Thank you for volunteering to maintain this code base forever. Much appreciated :-)

**Comment by AsgerPetersen** [comment]
I aim to please 😘

**Comment by AsgerPetersen** [comment]
160a8204e237b1739de3c0ff3514f19ed632257d added black to CI
