### ISSUE TITLE
Python dependencies

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/fikspunktsregister#17]
Should be specified at least for conda. But we may also have to use an other option for Oracle Linux. That other option could be plain old requirements.txt for pip of maybe a pipfile for pipenv?

Docker image should of course install deps automagically.

**Comment by bjornharrtell** [comment]
I see no reason why conda (https://conda.io/docs/glossary.html#miniconda-glossary) could not be used for all supported envs. Will see if I can get in into Oracle Linux for Docker and CI.

**Comment by bjornharrtell** [comment]
Looks like miniconda is working fine in Oracle Linux, see https://github.com/Septima/fikspunktsregister/pull/18.
