### ISSUE TITLE
Extraction of points within a given distance of a point

### ISSUE THREAD

**Issue by klavspc** [Septima/fikspunktsregister#48]
From https://github.com/Septima/fire-gama/issues/1#issuecomment-443729720:

> Først og fremmest skal man kunne søge efter observationer defineret ved afstand fra et centerpunkt og indenfor en tidsramme.

_Re: centerpoint_:

The API must support something along the line of:
`fireDb.getPointsWithin(pointId, distance)`

_Re: tidsramme_:

Observations need to be filtered; Should this be implemented as a filter functionality in the API or must the client filter?

**Comment by bjornharrtell** [comment]
Seems we have a good candidate for the first convenience API method to be implemented. My opinion is that the API should offer suitable filtering.

**Comment by AsgerPetersen** [comment]
If we only return a subset of observations for a point, I think the return type should be Observation and not Punkt. So method could be something like `firedb.hent_observationer_naer_punkt(punkt, afstand, tidfra, tidtil)`. Where punkt and afstand cannot be None. We could also have the more generic `firedb.hent_observationer_naer(pointgeom, afstand, tidfra, tidtil)` where pointgeom is a Geometry (not a Punkt).

**Comment by bjornharrtell** [comment]
^^ sounds good to me, will attempt to implement.

**Comment by bjornharrtell** [comment]
@AsgerPetersen I'm uncertain how to do distance filtering for this case... I would not assume GEOMETRIOBJEKT is "close enough"? And if that is true, the distance filtering becomes a pretty hairy thing...

**Comment by klavspc** [comment]
Please only return observations for which _both_ the opstillingspunkt and sigtepunkt is within the distance. Else the client would have to filter observations further which defies the purpose of having this convenience method.

Please note that fire-gama needs to list all punkter and then observationer between these. This means that I need to be able to go from observation to punkter in order to list all punkter. If this client code gets too messy then the convenience function is no convenience at all.

Question: Can this method be implemented without a _beregning_ parameter? Without such a parameter which coordinates would the API check against the distance parameter?

**Comment by kbevers** [comment]
> I would not assume GEOMETRIOBJEKT is "close enough"?

You can assume that it is :-)

**Comment by AsgerPetersen** [comment]
@kbevers is this how you want it:

> Please only return observations for which both the opstillingspunkt and sigtepunkt is within the distance.

**Comment by kbevers** [comment]
> @kbevers is this how you want it:

I guess that depends on how the search if made. If the search is "find all observations within this polygon", then yes, that is how I want it. But if the search is "find all observations from this point (opstillingspunkt) within radius x" then I only want observations between the originating opstillingspunkt and all possible sigtepunker. Does that makes sense?

**Comment by bjornharrtell** [comment]
It currently makes sense to me, thanks. 😄

**Comment by bjornharrtell** [comment]
@klavspc, master branch now has these methods on fireapi:

```python
    def hent_observationer_naer_opstillingspunkt(
        self,
        punkt: Punkt,
        afstand: float,
        tidfra: Optional[datetime] = None,
        tidtil: Optional[datetime] = None,
    )

    def hent_observationer_naer_geometri(
        self,
        geometri,
        afstand: float,
        tidfra: Optional[datetime] = None,
        tidtil: Optional[datetime] = None,
    )
```
