### ISSUE TITLE
Forbindelsesproblemer

### ISSUE THREAD

**Issue by kbevers** [Septima/fikspunktsregister#58]
I et forsøg på at forbinde til FIRE (altså den "rigtige" database på SDFEs netværk) løber jeg i nogle fejl jeg ikke helt forstår årsagen til. Når jeg kører følgende kode:

```
firedb = FireDb(f'{user}/{password}@{host}:{port}/{service}')
p = firedb.hent_punkt("ce5d92cb-e890-411b-a836-0b3f19564500")
```
bliver jeg mødt med
```
# udeladt: masse stack trace fra sqlalchemy
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-12545: Connect failed because target host or object does not exist (Background on this error at: http://sqlalche.me/e/4xp6)
```

Der er altså tilsyneladende ikke skabt en forbindelse til databasen. Det skal ses i lyset af at nedenstående fungerer fint:
```
con = cx_Oracle.connect(f'{user}/{password}@{host}:{port}/{service}', encoding="UTF-8", nencoding="UTF-8")
cur = con.cursor()
cur.execute('SELECT * FROM punkt')
```

Jeg bruger naturligvis det samme login info begge steder. Any ideas?

**Comment by kbevers** [comment]
Nevermind. Det var det evindelige problem med at finde ud af om det er database navnet eller service navnet der skal indgå i connection string. Der er hul igennem nu.

**Comment by AsgerPetersen** [comment]
SQLAlchemy bruger cx_oracle under hætten, og så vidt jeg husker skubber den connection string direkte videre til cx_oracle. Så hvis det virker i cx_oracle, så BURDE det også virke i SQLAlchemy.

**Comment by kbevers** [comment]
Desværre er *burde* ikke alting det der sker i virkeligheden :-) Anyway, det blev fikset ved at bruge denne connection string `{user}{pass}@{host}:{port}/firetest` istedet for `{user}{pass}@{host}:{port}/firetest.prod.sitad.dk` (som virkede med `cx_Oracle`). Det er min oplevelse at det ofte er noget bøvl med oracle at der er to måder at angive databasens navn på.

**Comment by AsgerPetersen** [comment]
SQLAlchemy giver ikke bare connection string videre. Se evt docs her https://docs.sqlalchemy.org/en/latest/dialects/oracle.html#module-sqlalchemy.dialects.oracle.cx_oracle
