### ISSUE TITLE
Default sqlalchemy echo mode shouldn't be debug

### ISSUE THREAD

**Issue by kbevers** [Septima/fikspunktsregister#60]
This becomes too when using FireDB in non-development code:

https://github.com/Septima/fikspunktsregister/blob/86456037396f69f870f40757c9f00e9aa19e3fc7/fireapi/firedb.py#L34-L36

I suggest something like:

```
class FireDb(object):
    def __init__(self, connectionstring, debug=False):
        """

        Parameters
        ----------
        connectionstring : str
            Connection string for the oracle database where the FIRE database resides.
            Of the general form 'user:pass@host:port/dbname[?key=value&key=value...]'
        """
        self.dialect = "oracle+cx_oracle"
        self.connectionstring = connectionstring
        self.engine = create_engine(
            f"{self.dialect}://{self.connectionstring}", echo=debug
        )
	...
```

and let the user decide which is needed. Right now I have no control over it unless I modify `firedb.py`.

**Comment by AsgerPetersen** [comment]
Agree

**Comment by bjornharrtell** [comment]
Fixed by https://github.com/Septima/fikspunktsregister/pull/61.

**Comment by kbevers** [comment]
Well, I just turned it of. Probably not so very helpful tests on CI?

**Comment by bjornharrtell** [comment]
Maybe it's ok. Otherwise I'll turn it back on eventually. :)
