### ISSUE TITLE
Strings from database should be read as UTF8

### ISSUE THREAD

**Issue by kbevers** [Septima/fikspunktsregister#62]
UTF8 characters in the database are not returned correctly by sqlalchemy. Danish characters get replaced by `?`'s. Here's an example: `Hj?rnet Irlandsvej - Gyldenrisvej.K?benhavns Belysningsv?sens Koblingsstation`. A workaround is to set the `NLS_LANG` environment variable:

```
import os
os.environ["NLS_LANG"] = "DANISH_DENMARK.UTF8"
from sqlalchemy.orm import aliased
from fireapi import FireDb
```

When I use cx_oracle I can fix it like this: `con = cx_Oracle.connect(f'{usr}/{pwd}@{server}:{port}/{service}', encoding="UTF-8", nencoding="UTF-8")`. Presumably there's a similar construct in sqlalchemy.

**Comment by AsgerPetersen** [comment]
It is documented here: https://docs.sqlalchemy.org/en/latest/dialects/oracle.html#unicode

**Comment by kbevers** [comment]
I've fixed it (or so it seems) in 5681a18. There may be other things needed, I remember cx_Oracle requiring several settings for CLOB's to be read properly.

**Comment by bjornharrtell** [comment]
Hmm where does that commit live? :)

**Comment by AsgerPetersen** [comment]
https://github.com/Septima/fikspunktsregister/pull/61

**Comment by kbevers** [comment]
> Hmm where does that commit live? :)

On the intertubes! :)

**Comment by bjornharrtell** [comment]
Various fixes to minor things :D

**Comment by AsgerPetersen** [comment]
in #64 I have added a unit test for round tripping utf8. And it fails on my machine and on CI.

On my machine it works if i add 

```python
os.environ["NLS_LANG"] = "DANISH_DENMARK.UTF8"
```
which obviously stinks...

**Comment by kbevers** [comment]
Yeah, see the same thing here. I must accidently have left the NLS_LANG thing in my code when I tested the `create_engine(..., encoding='utf8') change.

According to the sqlalchemy docs this shouldn't happen if the database is configured to use unicode. I have no idea what the default setting is. I am trying to find out how our database is set up.

**Comment by AsgerPetersen** [comment]
I think I have the solution
