### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/fikspunktsregister#71]
Are we going with this distribution method:
![image](https://user-images.githubusercontent.com/1392735/50679164-922e5600-1002-11e9-8261-48effb0dad51.png)
[Link](https://twitter.com/randyzwitch/status/1080871018598711298)

**Comment by kbevers** [comment]
Yes, please ship to Rentemestervej 8, 2400 København NV.

**Comment by AsgerPetersen** [comment]
As someone replied on Twiter:
> WorksOnMyMachine as a Service

**Comment by kbevers** [comment]
> WorksOnMyMachine as a Service

:-)

We are planning on using Conda for all software related to the new database. I haven't got a final plan for this yet, but it is likely that we will create a new channel containing the various libraries and applications that are needed for day to day work. *So*, packaging that works with Conda would be nice.

**Comment by klavspc** [comment]
@AsgerPetersen : In the [requirements section](https://github.com/Septima/fire-gama#requirements) for [fire-gama](https://github.com/Septima/fire-gama) I need to be able to link to installation instructions for fire api. Can you help me with a link to a paragraph in your readme.md? Something like https://github.com/Septima/fikspunktsregister#install

**Comment by busstoptaktik** [comment]
Closing: Partially superseded by #95 & #96 :-)
