### ISSUE TITLE
hent_punkt virker kun for identer af UUID-type

### ISSUE THREAD

**Issue by busstoptaktik** [Septima/fikspunktsregister#86]
Som i:

    >>> from fireapi import FireDb
    >>> db = FireDb("bla bla bla")

    >>> pt = db.hent_punkt("814E9045-962B-5A4E-E053-1A041EACF9E4")
    # det gik fint med UUIDen, men hvad med et GPS-nummer?
    >>> pt = db.hent_punkt("BUDP")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "b:\2019\projects\kvik\fikspunktsregister\fireapi\firedb.py", line 61, in hent_punkt
        .filter(p.id == punktid, p._registreringtil == None)
      File C:\Users\B004330\AppData\Local\Continuum\Anaconda2\envs\py37\lib\sitepackages\sqlalchemy\orm\query.py", line 2960, in one
        raise orm_exc.NoResultFound("No row was found for one()")
    sqlalchemy.orm.exc.NoResultFound: No row was found for one()
    >>>

... eller skal der bare en anden syntaks til?

**Comment by busstoptaktik** [comment]
NB: Ovenstående er et forsøg på at genskabe i REPL et problem (https://github.com/Kortforsyningen/fire-cli/issues/1), der manifesterede sig i @kbevers fire-cli  efter seneste opdatering af API, så jeg går ud fra at det skyldes en utilsigtet API-ændring.

Den relevante kode fra fire-cli er tilsyneladende:

    pi = aliased(PunktInformation)
    pit = aliased(PunktInformationType)

    try:
        punktinfo = (
            firedb.session.query(pi).filter(pi.infotypeid.like("IDENT:%"), pi.tekst == ident).one()
        )
        punkt = punktinfo.punkt
    except NoResultFound:
        try:
            punkt = firedb.hent_punkt(ident)
        except NoResultFound:
            firecli.print(f"Error! {ident} not found!", fg="red", err=True)
            sys.exit(1)

Jeg må tilstå at jeg ikke fatter hat af `aliased()` kaldene, så det er tænkeligt at jeg fejlfortolker hele vejen

**Comment by kbevers** [comment]
Problemet opstår fordi `PunktinformationType.infotypeid` er blevet omdøbt til `PunktinformationType.name`. Så der er ikke tale om en fejl i API'et. Fejlen er rettet i https://github.com/Kortforsyningen/fire-cli/commit/041b6f8cc9ea69825da5643d31cf7f237ac10fc5

En funktion, der som i `fire-cli`, tillader at søge efter et punkt på mere end bare UUID vil dog være en yderst brugbar API funktion.
